/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.view;

import domen.Korisnik;
import gui.view.components.TableModelKorisnik;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.Kontroler;

/**
 *
 * @author Nemanja
 */
public class FrmPretragaKorisnika extends javax.swing.JFrame {

    /**
     * Creates new form FrmPretraga
     */
    public FrmPretragaKorisnika() throws Exception {
        initComponents();
        pripremiTabelu();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtAdresa = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPonistiFiltere = new javax.swing.JButton();
        btnZavrsi = new javax.swing.JButton();
        btnUplata = new javax.swing.JButton();
        btnNoviKorisnik = new javax.swing.JButton();
        btnIzmeniKorisnika = new javax.swing.JButton();
        btnObrisiKorisnika = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Vrednost pretrage"));

        btnPretrazi.setText("PRETRAZI");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        jLabel1.setText("Ime");

        jLabel2.setText("Prezime");

        jLabel3.setText("Adresa");

        btnPonistiFiltere.setText("Ponisti filtere");
        btnPonistiFiltere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiFiltereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPonistiFiltere, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7)
                        .addComponent(btnPonistiFiltere))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btnZavrsi.setText("Zavrsi");
        btnZavrsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZavrsiActionPerformed(evt);
            }
        });

        btnUplata.setText("Uplata racuna");
        btnUplata.setEnabled(false);
        btnUplata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUplataActionPerformed(evt);
            }
        });

        btnNoviKorisnik.setText("Nov korisnik");
        btnNoviKorisnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoviKorisnikActionPerformed(evt);
            }
        });

        btnIzmeniKorisnika.setText("Izmeni korisnika");
        btnIzmeniKorisnika.setEnabled(false);
        btnIzmeniKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniKorisnikaActionPerformed(evt);
            }
        });

        btnObrisiKorisnika.setText("Obrisi korisnika");
        btnObrisiKorisnika.setEnabled(false);
        btnObrisiKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiKorisnikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZavrsi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUplata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNoviKorisnik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIzmeniKorisnika, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(btnObrisiKorisnika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnNoviKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUplata, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIzmeniKorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnObrisiKorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnZavrsi)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZavrsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZavrsiActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnZavrsiActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String adresa = txtAdresa.getText().trim();
        
        try {
            tabela.setModel(new TableModelKorisnik(Kontroler.getKontroler().dajNekekorisnike(ime, prezime, adresa)));
            if(Kontroler.getKontroler().dajNekekorisnike(ime, prezime, adresa).size()==0) throw new Exception();
            JOptionPane.showMessageDialog(this, "Sistem je nasao sledece korisnike po zadatoj vrednosti:", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
             JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje korisnika po zadatoj vrednosti.", "Greska!", JOptionPane.ERROR_MESSAGE);

        }
        
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnPonistiFiltereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiFiltereActionPerformed
       txtAdresa.setText("");
       txtIme.setText("");
       txtPrezime.setText("");
       
        try {
            tabela.setModel(new TableModelKorisnik(Kontroler.getKontroler().dajSveKorisnike()));
        } catch (Exception ex) {
            Logger.getLogger(FrmPretragaKorisnika.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPonistiFiltereActionPerformed

    private void btnUplataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUplataActionPerformed
        // TODO add your handling code here:
        TableModelKorisnik tmk = (TableModelKorisnik) tabela.getModel();
        try {
            FrmUplataRacuna frmur = new FrmUplataRacuna(Kontroler.getKontroler().dajSveNeplaceneZaSveUgovore(tmk.dajKorisnika(tabela.getSelectedRow()).getKorisnikId()));
            frmur.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FrmPretragaKorisnika.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUplataActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        btnUplata.setEnabled(true);
        btnIzmeniKorisnika.setEnabled(true);
        
        btnObrisiKorisnika.setEnabled(true);
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnIzmeniKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniKorisnikaActionPerformed
        // TODO add your handling code here:
                TableModelKorisnik tmk = (TableModelKorisnik) tabela.getModel();

        FrmDodajKorisnika dd = new FrmDodajKorisnika(tmk.dajKorisnika(tabela.getSelectedRow()));
        dd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIzmeniKorisnikaActionPerformed

    private void btnNoviKorisnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoviKorisnikActionPerformed
         FrmDodajKorisnika frmd = new FrmDodajKorisnika();
        frmd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNoviKorisnikActionPerformed

    private void btnObrisiKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiKorisnikaActionPerformed
         int dialogResult = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete izabranog korisnika?", "check again!", JOptionPane.YES_NO_OPTION);
                if (dialogResult == JOptionPane.NO_OPTION) return;
                else {
                    TableModelKorisnik tmk = (TableModelKorisnik) tabela.getModel();
             try {
                 if (Kontroler.getKontroler().dajSveZaJednogKorisnika(tmk.dajKorisnika(tabela.getSelectedRow()).getKorisnikId()).size()>0){
                     JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise korisnika jer postoje ugovori na njegovo ime", "Greska!", JOptionPane.ERROR_MESSAGE);
                     
                     return;
                 }
                 Kontroler.getKontroler().obrisiKorisnika(tmk.dajKorisnika(tabela.getSelectedRow()));
                  JOptionPane.showMessageDialog(this, "Sistem je obrisao korisnika", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
                  this.dispose();

             } catch (Exception ex) {
                  JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise korisnika", "Greska!", JOptionPane.ERROR_MESSAGE);

             }

                }
    }//GEN-LAST:event_btnObrisiKorisnikaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniKorisnika;
    private javax.swing.JButton btnNoviKorisnik;
    private javax.swing.JButton btnObrisiKorisnika;
    private javax.swing.JButton btnPonistiFiltere;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnUplata;
    private javax.swing.JButton btnZavrsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void pripremiTabelu() throws Exception {
        tabela.setModel(new TableModelKorisnik(Kontroler.getKontroler().dajSveKorisnike()));
    }
}
